# Generated by Django 4.0.5 on 2022-07-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.BinaryField()),
                ('field2', models.BooleanField()),
                ('field4', models.DateField()),
                ('field5', models.TimeField()),
                ('field6', models.DateTimeField()),
                ('field7', models.DurationField()),
                ('field9', models.BigIntegerField()),
                ('field10', models.FloatField()),
                ('field11', models.IntegerField()),
                ('field12', models.PositiveIntegerField()),
                ('field13', models.PositiveSmallIntegerField()),
                ('field14', models.SmallIntegerField()),
                ('field15', models.CharField(max_length=20)),
                ('field16', models.TextField()),
                ('field17', models.EmailField(max_length=254)),
                ('field18', models.FileField(upload_to='')),
                ('field19', models.FilePathField()),
                ('field21', models.GenericIPAddressField()),
                ('field22', models.SlugField()),
                ('field23', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
