# Generated by Django 4.0.5 on 2022-07-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_typefields_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='TypeFields',
        ),
    ]
